＃这是基本的工作流程，可帮助您开始使用操作

名称：CI

＃控制动作何时运行。
在：
  ＃在推送或拉取请求事件上触发工作流，但仅针对master分支
  推送：
    分支机构：[主管]
  pull_request：
    分支机构：[主管]

  ＃允许您从“操作”选项卡手动运行此工作流程
  workflow_dispatch：

＃工作流程运行由一个或多个可以顺序运行或并行运行的作业组成
职位：
  ＃此工作流程包含一个名为“ build”的作业
  建立：
    ＃作业将运行的运行者类型
    运行：ubuntu-latest

    ＃步骤代表将作为作业一部分执行的一系列任务
    步骤：
      ＃在$ GITHUB_WORKSPACE下签出您的存储库，以便您的工作可以访问它
      -用途：actions / checkout @ v2

      ＃使用runners shell运行一个命令
      -名称：运行单行脚本
        运行：echo您好，世界！

      ＃使用runners shell运行一组命令
      -名称：运行多行脚本
        运行：|
          echo添加其他操作来构建，
          回声测试，并部署您的项目。
